#!/usr/bin/env bash

# Installs Dot on a machine.
#
# Intended to be invoked remotely via a command like:
# bash -c "$(curl -fsSL https://raw.github.com/sds/dot/master/bootstrap/remote-install)"

DOT_INSTALL_DIR="$HOME/.dotfiles"

mkdir -p $DOT_INSTALL_DIR && \
  curl -L https://github.com/sds/dot/tarball/master | \
  tar xz --strip 1 -C $DOT_INSTALL_DIR

(cd $DOT_INSTALL_DIR && ./install)
