#!/usr/bin/env sh

# Check for updates to the repository and install them.
# Returns exit status of -1 if no updates were found.

set -e # Halt on first error

# Define DOTDIR to be location of this repository
export DOTDIR="$( cd "$( dirname "$0" )" && pwd )"

source "$DOTDIR/bootstrap/init.sh"
source "$DOTDIR/bootstrap/setup.sh"
source "$DOTDIR/bootstrap/update.sh"

update_dot
